export * from "./cartReducer"
export * from "./productReducer"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"
export const ENABLE_LOADING = "ENABLE_LOADING"

export const SET_COST_FILTER = "SET_COST_FILTER"
export const REMOVE_COST_FILTER = "REMOVE_COST_FILTER"

export const SET_COLOUR_FILTER = "SET_COLOUR_FILTER"
export const REMOVE_COLOUR_FILTER = "REMOVE_COLOUR_FILTER"


export const SET_DESIGN_TEMPLATES_FILTER = "SET_DESIGN_TEMPLATES_FILTER"
export const REMOVE_DESIGN_TEMPLATES_FILTER = "REMOVE_DESIGN_TEMPLATES_FILTER"


export const SET_TYPE_FILTER = "SET_TYPE_FILTER"
export const REMOVE_TYPE_FILTER = "REMOVE_TYPE_FILTER"

export const APPLY_FILTER = "APPLY_FILTER"
